# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: main
    init: chmod +x ./install_cryptoescudo.sh && ./install_cryptoescudo.sh
    command: cryptoescudo/cryptoescudod --datadir=/workspace/cryptoescudo-playground/cryptoescudo/data/ --daemon
  - name: debug.log
    command: sleep 5 && tail -f cryptoescudo/data/debug.log
    openMode: split-right    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
