# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: cryptoescudod
    init: getdaemon.sh
    command: cryptoescudo/cryptoescudod -datadir=data/ -daemon
  - name: debug.log
    command: tail cryptoescudod/data/debug.log
    openMode: split-right    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
